# Generated by Django 3.0.8 on 2020-07-07 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('photo_url', models.CharField(max_length=512)),
                ('post_timestamp', models.DateTimeField(auto_now_add=True)),
                ('section_name', models.CharField(choices=[('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('News', 'News')], default='Fashion', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='draft', max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-post_timestamp',),
            },
        ),
    ]
