# Generated by Django 3.0.8 on 2020-07-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTFA', '0002_auto_20200710_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel_urls',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
    ]
