# Generated by Django 3.0.8 on 2020-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTFA', '0003_post_carousel_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carousel_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
