# Generated by Django 3.0.8 on 2020-07-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogTFA', '0005_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ('email',)},
        ),
    ]
